# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_pub_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_time',
        ),
    ]
