# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article__time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='_time',
        ),
    ]
